ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(40) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_name VARCHAR(60) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_url VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '';