ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram VARCHAR(120) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(60) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS about TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_email BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_new_lesson BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_cancel BOOLEAN DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS lesson_cancellations (
    id SERIAL PRIMARY KEY,
    lesson_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    reason TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (lesson_id, student_id)
);